### ISSUE TITLE
Can I add this feed to my app?

### ISSUE THREAD

**Issue by theothernt** [RobinFrcd/AerialShots#2]
Hi,

[I maintain an app called Aerial Views](https://github.com/theothernt/AerialViews). It's similar to Aerial on the Mac, except it's for Android TV.

Aerial Views only supports Apple videos currently, but I'd like to add your community videos if that's ok?

**Comment by RobinFrcd** [comment]
Sure, feel free to use them ! (I'll add more of them before the end of the year)

**Comment by theothernt** [comment]
Thank you and I look forward to more videos!
