### ISSUE TITLE
Issues with video playback and category

### ISSUE THREAD

**Issue by theothernt** [RobinFrcd/AerialShots#4]
I think I've discovered a couple of issues...

###  Video playback
The 10 new videos from Reunion Island seem to stutter when not using Apple's video player framework (or QuickTime).

On the Mac, if you use VLC to play the clips, they stutter quite badly. On Android TV, it's nowhere near as bad but they do stutter if you watch the corner of the screen.

Your original videos from Norway and the French Alps are very smooth at 30fps when played with QuickTime, VLC or on Android TV btw.

### Video category
In the manifest the 1080p HEVC videos are added under the 'url-1080-HDR' key. I think it should be 'url-1080-SDR' as these videos don't contain any HDR10, HDR10 Plus or Dolby Vision metadata so HDR doesn't activate on a TV or Mac with a HDR display (tested on a MacBook Pro M2).

Thank you again for making the videos available!

**Comment by RobinFrcd** [comment]
Hello, thanks for your feedback !
You have the issue with both 4K and 1080p or only the latter ?

**Comment by theothernt** [comment]
> Hello, thanks for your feedback ! You have the issue with both 4K and 1080p or only the latter ?

The HEVC 4K and 1080p versions stutter in VLC but H.264 version seems fine.

**Comment by RobinFrcd** [comment]
Is the stutter really noticeable on VLC ? I've tried with `VLC: Version 3.0.17.3 Vetinari (Apple Silicon)` on a M1 Air, I don't see any noticeable stutter.
I can try to re-export the video with the latest version of FinalCut in a few days once I have a more powerful mac in the hands !

**Comment by theothernt** [comment]
> Is the stutter really noticeable on VLC ? I've tried with `VLC: Version 3.0.17.3 Vetinari (Apple Silicon)` on a M1 Air, I don't see any noticeable stutter. I can try to re-export the video with the latest version of FinalCut in a few days once I have a more powerful mac in the hands !

Just checked, I have the latest VLC too...

I did some more testing on an older PC and Mac (both Intel based). They don't seem to have the stutter problem I mentioned so it may be limited to the M2... I have no idea why ?!

Anyway, happy to do more testing in a few days!

**Comment by RobinFrcd** [comment]
Really strange indeed, did you have some users of Aerial Views reporting the issue, or you're the first one to notice it ?

**Comment by theothernt** [comment]
> Really strange indeed, did you have some users of Aerial Views reporting the issue, or you're the first one to notice it ?

It's just me as the videos haven't been added yet. 

Unlike Aerial for Mac, I have to update the list of video manually with each app update. This is partly because I modify the manifest a bit to allow for translations.

**Comment by theothernt** [comment]
Some updates...

### Videos
The new videos have been running in my app for over a month now and no problems have been reported so this issue can be closed.

### Manifest
A user just reported a mistake with one of the video links...

Incorrect link:
https://github.com/RobinFrcd/AerialShots/releases/download/reunion-2022/robinfrcd_reunion_CapMechan2_1080p_hevc.m4v

Correct link:
https://github.com/RobinFrcd/AerialShots/releases/download/reunion-2022/robinfrcd_reunion_CapMechant2_1080p_hevc.m4v
